### ISSUE TITLE
Captions in Netflix

### ISSUE THREAD

**Issue by ghost** [JoeKuhns/PiedPiPer.safariextension#6]
I don't know if this is something you can fix or not, but when in PIP mode the captions stay in the Netflix browser and don't show in the PIP screen.

**Comment by JoeKuhns** [comment]
Yeah, I know.  Netflix captions are a layer in the html and not a CC stream in the video.  I have been reading about ways to reincorporate the caption to the vide, but I'm not sure is I have the chops to do it.  Also the new version of Netflix that they have been demoing will break part of the plugin completely, so that is my first focus.

**Comment by JoeKuhns** [comment]
Same as #3

**Comment by JoeKuhns** [comment]
Sorry, I have to close this.  Without standard captions, Netflix captions are going to be extremely difficult if not impossible to add to the PIP.  I'll keep it on the list, but support is unlikely for now.
